### ISSUE TITLE
Add support to backup/restore alert rules

### ISSUE THREAD

**Issue by fayak** [esnet/gdg#108]
Problem:
I use grafana alerting system where I put alert rules in grafana directly. I would like them also to be backed-up like everything else

Solution:
Having a way to backup alert rules like dashboards, datasources, etc

alternatives:
[grafana alerts exporter.](https://github.com/youngpabl0/grafanaalertsexporter)
this is a bit basic though, and I already appreciate very much gdg. I would like to be able to use only gdg for both dashboards and alert rules

**Comment by safaci2000** [comment]
There's a few tickets that are somewhat blocked right now.  There's an official go client built based on the swagger / OpenAPI definition that's being worked on.  https://github.com/grafana/grafana/issues/47827.  

Once that's finalized, I plan on moving GDG over to it which opens up a lot more options as to what to support. 

Currently we're using: https://github.com/grafana-tools/sdk.  Anything on there I'm happy to add which is usually trivial.  Otherwise need to patch the SDK, wait for upstream to pull that in.  Once those changes are approved I can pull them into GDG. 

I'll check in with the grafana team to see what the status is.  Though I assume with the ticket still open it's not official yet.

**Comment by laertis** [comment]
# Setup

With
- gdg 0.5.1

To backup `Grafana v7.2.0` I run
```
gdg backup alertnotifications download
gdg backup connections download
gdg backup dashboards download
gdg backup folders download
gdg backup organizations download
gdg backup teams download
gdg backup users download
```

To restore in `Grafana v7.5.17` I run
```
gdg backup organizations upload
gdg backup folders upload
gdg backup teams upload
gdg backup users upload
gdg backup connections upload
gdg backup alertnotifications upload
gdg backup dashboards upload
```

# Problem
In `Grafana v7.5.17` where I restored from the `Grafana v7.2.0` backup, although I'm able to see the the alerts configured in individual panels in the `Alert` tab when I edit the panel, I cannot see any alert rule under `http://<grafana_url>/alerting/list`
Moreover, the "heart" icon is missing from the panel that has the configured alert

Would you know why this might happen and how to solve it ?
