### ISSUE TITLE
(UI/UX) I just deleted all my dashboards with this tool lol. (oops)

### ISSUE THREAD

**Issue by perfectra1n** [esnet/gdg#159]
**Is your feature request related to a problem? Please describe.**
I was confused when initially using this tool to download / backup my Dashboards. There are import and export functions, so I (mistakenly) assumed that this was in terms of the remote Grafana instance, so I completely deleted all my Dashboards.

**Describe the solution you'd like**
Perhaps instead of "import" and "export", "upload" and "download" or something of the sort could be used, in terms of the local machine?

**Describe alternatives you've considered**
I mean I wouldn't be against qualifying myself as braindead to be honest, so there's always the vegetative alternative.

**Additional context**
Let me know if there's a way to recover my deleted dashboards, if not, perhaps changing the language / validating that if the command is "interactive" that you confirm that you will be overwriting data. If it's not interactive, well there's no saving that interaction, go ahead and overwrite the data.

**Comment by vincent-gou** [comment]
Totally agree with upload / download instead of import / export it should limit misunderstanding 🤞

**Comment by safaci2000** [comment]
I'm happy to add aliases to upload/download.  I don't think we should drop importer/export as a being supported, since that's a breaking change.  I can add a 'upload' and 'download' if that's more intuitive.  GDG was initially modeled after a different tool which used the same behavior.  

I'm sorry you lost all the dashboards, I'll take a pass at this and see if I can replace download / upload and leave the import/export aliases, but all actions for GDG are from the Grafana perspective, you're importing data from Grafana and exporting to Grafana.  I really do suggest reading the user guide.  I try to make sure there is some docs for each feature beyond the CLI on https://software.es.net/gdg/ Hopefully some more tutorials will be added over time. 


Will have a feature change to change this to be a bit more intuitive.  I'll likely only do this once, so is download/upload preferred? Is there any other suggestion we should consider?

**Comment by vincent-gou** [comment]
When reading documentation it's clear that is import / export are doing what's explained. But saddly i (or maybe we) read docs after we encounter an issue...
Aliases would be perfect ! Thanks

**Comment by perfectra1n** [comment]
It's all good! I'm also incredibly dense. Honestly taking a look at the docs [here](https://software.es.net/gdg/docs/gdg/usage_guide/#dashboards) vs. what the `help` displays would be great (whose help string repeats the same verb as the command):
<img width="748" alt="image" src="https://user-images.githubusercontent.com/2390633/235575323-b1e84500-1701-4d19-b428-56c7d9c29921.png">

The User Guide certainly does a better job explaining the context of the command, maybe even just tossing the comments from the commands in the above URL, into the `import` and `export` help output so that it reads:

```bash
Available Commands:
  clear       Deletes all dashboards
  export      Exports all dashboard from local filesystem (matching folder filter) to Grafana
  import      Import all dashboards from grafana to local file system
  list        Lists all current dashboards
```

Instead of the current:
```bash
Available Commands:
  clear       delete all monitored dashboards
  export      export all dashboards
  import      Import all dashboards
  list        List all dashboards
```

I was just winging it, and I own that lol. I figured that since I just wanted to download the dashboards that the command couldn't be too bad. I knew I was playing with fire after reading the help output of "export     export all dashboards" and "import     import all dashboards" lol. Yeah my brain goes immediately to thinking in the context of the local filesystem, which is why I went straight to `export`. Thanks for taking the time to make this though, I love it, and I've been using it daily to backup/download/modify my **_new and improved_** dashboards after recreating them! lol

**Comment by andyantrim** [comment]
I've also been caught by this :) (Thankfully after already backing things up!) 

For what it's worth, in grafana UI it is:
**export**: downloads dashboard JSON
**import**: upload a dashboard from JSON

So I think this tool does go against that, however can't change that without breaking stuff :)

For what it's worth the alias does seem to be the way forward. I like @perfectra1n 's suggestion of better output from `help` (but who reads those anyway lol). It could be an idea of moving the main command to `download` and `upload` and making the original commands aliases?

**Comment by safaci2000** [comment]
@andyantrim Sure, but it's always about who the subject is.  If the Grafana is the 'subject' you're importing into grafana or exporting out of grafana.  If Grafana is the service doing the work that makes sense.  

If you have another tool, then you're pulling data from grafana (importing) and writing data to grafana (exporting).

Anyways, there's a patch that's switching it to download/upload since enough people have been caught by this, I'll just change the wording.

**Comment by davidgiga1993** [comment]
Same thing happened to me.. amazing. A warning or a more detailed description would be nice.
Additionally there is no handling if the source and destination folder is the same, pretty horrible UX tbh.

**Comment by perfectra1n** [comment]
Hey @safaci2000 would you be open to just bumping the version of `gdg` since this issue appears to be affecting others? Just installing the latest via `go`, the version doesn't include the updated output. It might save a few people if you were to just bump it :)

**Comment by safaci2000** [comment]
I'll do a release soon.  I would like to take a closer look at some of the changes pending.  Let me get the folder permissioning in that's in PR and I'll push this in along with a confirmation before clearing the dashboards I added recently.

**Comment by safaci2000** [comment]
@perfectra1n I release 0.4.5 that includes all the changes in this ticket. Also added a warning before uploading the dashboards.  @davidgiga1993.  

Let me know if you have any other suggestions to make gdg more intuitive to use.
