### ISSUE TITLE
Add version notes to grafana dashboard when exporting/uploading

### ISSUE THREAD

**Issue by vincent-gou** [esnet/gdg#161]
**Is your feature request related to a problem? Please describe.**
When exporting / Uploading dashboards could it be possible to add a note ?
After an upload version info from source Grafana Dashbaord is not kept and it could be interesting to have a way to add a note when exporting to Grafana. 
I didn't check if Grafana API permit this.

**Describe the solution you'd like**
Add an way to add a note during dashboard export / upload to Grafana. It could permit to follow historical versions of a dashbaord when stored outside Grafana and uploaded in different Grafana instances.

![image](https://user-images.githubusercontent.com/46958513/235489822-9d656310-b7cd-435c-bf92-0f8b3bd6f03a.png)

**Describe alternatives you've considered**
None yet.

**Additional context**
Big picture would be to manage dashboard versioning outside Grafana.

**Comment by safaci2000** [comment]
If this is easily supported I don't mind adding it but I do think you're mixing concepts here. 

1. GDG is designed to have a white list. (Though we have flags that ignore those) where the folders specified we're assuming GDG is in charge of managing. 

That assumed data is in some type of version control.  It's destructive to the grafana data since it assumed that the .json is the source of truth not grafana. 

You make changes, pull them into git, and update all environment using gdg one you're happy with those charges. Ideally staging, dev and prod etc

2. The alternative is to have dashboard as code. You write something that will generate a dashboard. It's outside gdg scope but it ignores and changes in grafana and bikes the data everytime. If you need changes persisted your change the json/yaml etc that describes the dashboard. 

3. You use grafana as a version system and let it manage the versions. You backup the database and restore if some disaster happened. 

What you're describing feels like you're missing #1 and #3. If the API supports it we can add that in but it's value may be limited.

For example we could have a version data in there, but GDG may wipe all dashboard before adding them in. That'll remove all grafana brain history.  (I'm not sure if that's the current behavior tbh but that's a legitimate behavior by gdg. It's only goal is to make grafana look like the local file system for the given folders it has been configured for )


Does that make sense?

**Comment by vincent-gou** [comment]
Hi @safaci2000 , thanks for your feedback and job done !

I totally agree with #1, #2 is not as mature as i could expect or too difficult to implement (for me) and  #3 is partially what i currently use.

I'm using #1 a lot through dashboards tags and folders watched.

I'm maybe using Grafana a different way than it should  (Grafana instance budget or IT issue) but i'm developping dashbaords locally (DEV) and pushing them when they're ready for TESTING or PROD.

Actually, those dashbaords are templated as much as possible and delivered to different orgs and clients (so different Grafana instances and DataSources). 

Destination dashbaords are not aimed to be updated by destination audience. An uploaded dashbaord with a **version** information would be interesting (in my case), if that fit more use cases for others it will perfect.

To resume, i don't really care of grafana versionning but more in JSON versionning from GDG import/download with versionning managed outside GDG. 

Erasing Dashboards history when importing/uploading is not an issue. But keep trace of DEV version used would be nice.

Thanks

**Comment by safaci2000** [comment]
@vincent-gou I'm going to close this out.  There is no API that I can see that lets you import the notes.  If that changes feel free to re-open.  

You can see all the various API from their swagger spec.  Easiest way I found is to go to this [site](https://petstore.swagger.io/) and just point the swagger spec of grafana which is found on [here](https://raw.githubusercontent.com/grafana/grafana/main/public/api-merged.json) and it'll show you all the various supported APIs.
