### ISSUE TITLE
checksum fail

### ISSUE THREAD

**Issue by elervik** [esnet/gdg#97]
Go install fails the checksum on the downloaded binary and the checksum provided by checksum database.

```
$ go install github.com/esnet/gdg@latest
go: downloading github.com/esnet/gdg v0.1.11
go: github.com/esnet/gdg@latest: github.com/esnet/gdg@v0.1.11: verifying module: checksum mismatch
	downloaded: h1:CnDtASXmMzHJ9l2BX5zTnOpSpbQcVvko0pbW8vI/UrU=
	sum.golang.org: h1:0b0aapElYX2+d9RLvDoPOrWZZ1FbJoFwPtCLQVb1Tyc=
SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
```

https://go.dev/ref/mod#authenticating

**Comment by safaci2000** [comment]
hey @elervik .  Thanks for reporting this.  Not sure how this broke, but I since I had a breaking change in the config and in go.mod (replace directive), I just re-released this.  0.2.1 is the latest which should work with go install.  You can always grab the binary from the install page, though go install should be working.
