### ISSUE TITLE
export from specific local folder to grafana

### ISSUE THREAD

**Issue by pahla1** [esnet/gdg#99]
Hi all,

I have multiple grafana instances with many folders and wanna sync my folders from one dc to another. Can we have an option to import a folder from grafana at DC1 to my local folder `dashboards/DC1` and then switch context to DC2 and export `dashboards/DC1` to grafana at DC2? let me also say that I don't want to change `output_path` of dc2 to `dashboards/DC1`. I need it  for example as an command line argument.

Thanks in advance.

**Comment by safaci2000** [comment]
Can I ask why you don't want to change the output folder?  The only use case I have that is similar to yours is synching staging to prod or vice versa.  I track the changes in git which is the reason for this tool (Also [wizzy](https://github.com/grafana-wizzy/wizzy) was no longer maintained).  I simply have a staging.yml and prod.yml and point to each one accordingly.  I find it less error prone than switching contexts around.  

You already have an option to filter by folder on imports  -f folder Name.  So you could do something like.

gdg -c conf/dc1.yml importer -f foobar
gdg -c conf/dc2.yml export -f foobar

Otherwise, this is a larger task than simply adding a CLI arg.  It's a whole new concept being introduced to the app. Everything that it's doing right now is based on a single context.  

If you want to d a PR i'm happy to look at it, but otherwise this likely will not happen for a while.
